// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, PortableTextBlock } from "emdash";

export interface Página {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  content?: PortableTextBlock[];
  image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  subtitle?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Trabalho {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  location?: string;
  coordinates?: string;
  image: { id: string; src?: string; alt?: string; width?: number; height?: number };
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Serviço {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  description?: string;
  icon?: string;
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

declare module "emdash" {
  interface EmDashCollections {
    pages: Página;
    portfolio: Trabalho;
    services: Serviço;
  }
}